### PR TITLE
fix: Simplify comparison code to not use unicode regexp flag

### PR DESCRIPTION
**Pull request by thomaschaaf**

### CODE REVIEW

**Comment by yeldiRium** [comment]
Hi @thomaschaaf,

thanks for the contribution. I like not using a regexp here, since it avoids the named-capture-group thing as well as the unicode flag.

However currently the tests break. Can you please add the options `t` and `y` to the array?

Kind regards,
yeldiR

**Comment by yeldiRium** [comment]
Ah you were quicker than I could respond :)

**Comment by thomaschaaf** [comment]
> Ah you were quicker than I could respond :)

sorry I developed in the browser :D

**Comment by goloroden** [comment]
@thomaschaaf Thanks for the updated PR 😊 

One last thing before being able to merge this: Would you mind adding yourself as a contributor to the `package.json` file?

**Pull request merged**
