### PR TITLE
feat: Adds TypeScript definition file.

### PR DESCRIPTION
**Pull request by ryansmith94**
Hey @thenativeweb, thanks for this package, been using it a lot here @ht2-labs where we use TypeScript. Unfortunately, when we use it with TypeScript we have to keep creating this definition file for the package, hopefully you're happy to merge this so it's easier to use with TypeScript 👍

### CODE REVIEW

**Comment by goloroden** [comment]
Hi @ryansmith94 😊 

Thanks for the nice words, and thanks for the pull request!
Basically, it LGTM 👍 

Just one question: Inside the type definition file, you use a helper function `createBoolean`. Is this necessary or could we skip it (as the `index.js` file also does not have such a function)?

**Comment by ryansmith94** [comment]
Hey @goloroden, you're very welcome. Unfortunately it's necessary, I couldn't figure out a way to put the type on the `export` itself so I had to define a new variable called `createBoolean` and assign the type to that before assigning it to the export. I could rename the variable to something else though if you like? I wanted to just call it `boolean` to match the code but that's a keyword in TypeScript.

**Comment by ryansmith94** [comment]
No worries 👍 Awesome. No that's cool, I don't mind, I'll do that now.

**Comment by ryansmith94** [comment]
Hi @goloroden, if you get a sec please can you release this to npm?

**Comment by goloroden** [comment]
I was previously only online via my mobile, but now I'll do 😊

**Comment by ryansmith94** [comment]
Ah no worries, thank you 👍

**Pull request merged**
