### PR TITLE
Added support for primitive object wrappers (fixes #295)

### LINKED ISSUE #295: Wrong result with primitive object wrappers
While I know it is advised not to use primitive object wrappers, you might still want to look into this:

```
const truthy = new String('true')
console.log(boolean(truthy)); // => false
```

A more robust approach would be doing something like this:

```
switch (Object.prototype.toString.call(value)) {
  case '[object String]':
    return [ 'true', 't', 'yes', 'y', 'on', '1' ].includes(value.trim().toLowerCase());
  case '[object Number]':
    return value.valueOf() === 1;
  case '[object Boolean]':
    return value.valueOf();
  default:
    return false;
}
```

### PR DESCRIPTION
**Pull request by smares**
Added support for primitive object wrappers (fixes #295)

### CODE REVIEW

**Review by goloroden — APPROVED** [review]

**Comment by goloroden** [comment]
Hi @smares 👋 

Thanks a lot for coming up with this PR 😊 
The changes look good, however, there a few things that need to changed.

First, code analysis now fails – you can see this when you run `npx roboter` on your machine. Can you please disable the rules for the affected lines using `eslint-disable-next-line`?

Second, the documentation should be updated as well. It's probably enough to have one sentence pointing out that it also works with the object wrappers, however it would be great if you could add this to the `README.md` file.

Last but not least, I wanted to ask if you would like to add yourself to the list of contributors in the `package.json` file?

**Comment by smares** [comment]
When I run `npx roboter` on my Windows machine, this is the output I get:

```
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
▸ Running quality assurance...
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
▸ Running code analysis...

Oops! Something went wrong! :(

ESLint: 7.26.0

No files matching the pattern "'lib/boolean.ts'" were found.
Please check for typing mistakes in the pattern.

✗ Malformed code found.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Code malformed.
  Error: Code malformed.
    at analyseTask (C:\Users\Sebastian\Documents\Projekte\boolean\node_modules\roboter\lib\cli\tasks\analyse.js:25:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.run (C:\Users\Sebastian\Documents\Projekte\boolean\node_modules\roboter\lib\cli\commands\qa.js:38:5)
    at async C:\Users\Sebastian\Documents\Projekte\boolean\node_modules\roboter\lib\bin\roboter.js:113:5
⠋
```

That `No files matching the pattern "'lib/boolean.ts'" were found.` line is weird, I am running roboter from the project root.

Not sure if this is caused by the previous line, but I can't seem to get rid of the `✗ Malformed code found.`. Tried with both `// eslint-disable-next-line no-new-wrappers unicorn/new-for-builtins` and `// eslint-disable-next-line`.

Any idea what I am doing wrong?

**Comment by goloroden** [comment]
@smares Well, we do not currently support running `roboter` on Windows, so it may just be that it doesn't work because of the OS. (However, we will change this in the next version, which is currently under development.)

So, thanks for the updates, I'll have a look at them, and get back to you as soon as possible 😊

**Review by goloroden — APPROVED** [review]

**Review by goloroden — APPROVED** [review]

**Comment by goloroden** [comment]
@smares I've just added a few missing commas, and merged it now – will be live on npm in a few minutes. Thanks once again for all your work 😊

**Pull request merged**
